---
title: "Coursework 2 - Arima"
author: 'Rivyesch Ranjan'
date: "2023-04-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Importing required libraries
library(dplyr)
library(ggplot2)
library(forecast) 
library(smooth)
library(Metrics)
```

## Data Pre-processing
```{r}
# Importing cleaned data from coursework 1
data <- read.csv('cleaned_data.csv',header=T)
dates <- data$date_obj

# create ts object
ts_data <- ts(data$values_no_na, frequency = 7)

# split time series into train and validation sets (90:10 ratio)
total_obs <- length(ts_data)
split_ts <- ts_split(ts.obj = ts_data, sample.out = round(0.1*total_obs))
train_set <- split_ts$train
val_set <- split_ts$test

# verify length of each set
length(train_set)
length(val_set)
```

```{r}
diff_train_7 <- diff(train_set, lag = 7)
diff_val_7 <- diff(val_set, lag = 7)

diff_train_7_1 <-  diff(diff(train_set, lag = 7), lag = 1)
diff_val_7_1 <- diff(diff(val_set, lag = 7), lag = 1)

diff_7 <- diff(ts_data, lag = 7)
diff_7_1 <- diff(ts_data, lag = 7) %>% diff()

tsdisplay(diff_7_1)
tsdisplay(diff_7)
```

## Seasonal and Trend Differenced
AR1, AR2 or AR3
spike at lag 1 in the ACF suggests a non-seasonal MA(1) component
significant spike at lag 7 in the ACF suggests a seasonal MA(1) component 
PACF also has sig spike at lag 7
begin with an ARIMA(0,1,1)(0,1,1)7 model

```{r}
# based on ACF and PACF 
fit <- Arima(train_set, order = c(0,1,1), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(0,1,1), seasonal = c(0,1,1)))$fitted)
```

```{r}
# increase non-seasonal MA component after looking at ACF of SARIMA(0,1,1,0,1,1)
fit <- Arima(train_set, order = c(1,1,1), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(1,1,1), seasonal = c(0,1,1)))$fitted)
```

```{r}
# increase non-seasonal MA component after looking at ACF of SARIMA(0,1,1,0,1,1)
fit <- Arima(train_set, order = c(1,1,1), seasonal = c(1,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(1,1,1), seasonal = c(1,1,1)))$fitted)
```

```{r}
# increase non-seasonal MA component after looking at ACF of SARIMA(0,1,1,0,1,1)
fit <- Arima(train_set, order = c(0,1,1), seasonal = c(1,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(0,1,1), seasonal = c(1,1,1)))$fitted)
```

```{r}
# increase non-seasonal MA component after looking at ACF of SARIMA(0,1,1,0,1,1)
fit <- Arima(train_set, order = c(1,1,1), seasonal = c(0,1,2))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(1,1,1), seasonal = c(0,1,2)))$fitted)
```

```{r}
# increase non-seasonal MA component after looking at ACF of SARIMA(0,1,1,0,1,1)
fit <- Arima(train_set, order = c(1,1,2), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,1,2), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,1,2), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(1,1,2), seasonal = c(0,1,1)))$fitted)
```

```{r}
# increase non-seasonal MA component after looking at ACF of SARIMA(0,1,1,0,1,1)
fit <- Arima(train_set, order = c(2,1,1), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(2,1,1), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(2,1,1), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(2,1,1), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(1,1,2), seasonal = c(0,1,2))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,1,2), seasonal = c(0,1,2)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,1,2), seasonal = c(0,1,2)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(1,1,2), seasonal = c(0,1,2)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,1,1), seasonal = c(0,1,2))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(2,1,1), seasonal = c(0,1,2)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(2,1,1), seasonal = c(0,1,2)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(2,1,1), seasonal = c(0,1,2)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,1,1), seasonal = c(1,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(2,1,1), seasonal = c(1,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(2,1,1), seasonal = c(1,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(2,1,1), seasonal = c(1,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(1,1,2), seasonal = c(1,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,1,2), seasonal = c(1,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,1,2), seasonal = c(1,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(1,1,2), seasonal = c(1,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,1,2), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(2,1,2), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(2,1,2), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(2,1,2), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,1,2), seasonal = c(0,1,2))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = length(val_set)))
forecast::accuracy(forecast(fit), val_set)[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(Arima(x, order = c(2,1,2), seasonal = c(0,1,2)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(2,1,2), seasonal = c(0,1,2)), h = 14))^2, na.rm=TRUE))

Metrics::smape(val_set, forecast(Arima(ts_data, order = c(2,1,2), seasonal = c(0,1,2)))$fitted)
```

## Seasonal Differenced
```{r}
fit <- Arima(train_set, order = c(1,0,0), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), test)

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,0,0), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,0,0), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), test)

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,0,0), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,0,1), seasonal = c(0,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), test)

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,0,0), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,0,1), seasonal = c(1,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), test)

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,0,0), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,0,1), seasonal = c(2,1,1))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), test)

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,0,0), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)))$fitted)
```

```{r}
fit <- Arima(train_set, order = c(2,0,1), seasonal = c(2,1,2))
fit
checkresiduals(fit)
ggtsdisplay(residuals(fit))
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), test)

arima_func <- function(x, h) {forecast(Arima(x, order = c(1,0,0), seasonal = c(0,1,1)), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(Arima(ts_data, order = c(1,0,0), seasonal = c(0,1,1)))$fitted)
```

## Auto Arima
```{r}
fit <- auto.arima(train_set)
fit
checkresiduals(fit)
autoplot(forecast(fit, h = 14))
forecast::accuracy(forecast(fit), length(val_set))[,c(2,3,5,6)]

arima_func <- function(x, h) {forecast(auto.arima(train_set), h = h)}
cv_model <- tsCV(ts_data, arima_func, h = 14)
sqrt(mean(cv_model^2, na.rm=TRUE))
sqrt(mean(residuals(forecast(auto.arima(ts_data), h = 14))^2, na.rm=TRUE))

Metrics::smape(test, forecast(auto.arima(ts_data))$fitted)
```

